<a href="https://colab.research.google.com/github/YENCHENGYOU/Comp576_hw/blob/main/Comp576_hw0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# =====================================================
# Task 2: MATLAB -> NumPy Linear Algebra Equivalents
# =====================================================

import numpy as np
import scipy.linalg as linalg
from numpy.random import default_rng

print("===== Step 1: Array properties =====")
a = np.array([[1, 2, 3], [4, 5, 6]])
print("Array a:\n", a)
print("ndims:", a.ndim)
print("numel:", a.size)
print("size:", a.shape)
print("size of 2nd dimension:", a.shape[1])

print("\n===== Step 2: Indexing & slicing =====")
print("last element:", a[-1,-1])
print("second row:", a[1,:])
print("first row to second row:", a[:2,:])
print("last 2 rows:", a[-2:,:])
print("every other row:", a[::2,:])
print("transpose:", a.T)

print("\n===== Step 3: Matrix operations =====")
b = np.array([[7,8],[9,10]])
a2 = np.array([[1,2],[3,4]])
print("Matrix multiply a2 @ b:\n", a2 @ b)
print("Elementwise multiply a2 * b:\n", a2 * b)
print("Elementwise divide a2 / b:\n", a2 / b)
print("Elementwise power a2**3:\n", a2**3)
print("Conjugate transpose a2.conj().T:\n", a2.conj().T)

print("\n===== Step 4: Special matrices =====")
print("zeros 3x4:\n", np.zeros((3,4)))
print("ones 3x4:\n", np.ones((3,4)))
print("identity 3x3:\n", np.eye(3))
rng = default_rng(42)
print("random 3x4:\n", rng.random((3,4)))
print("linspace 1 to 3, 4 points:\n", np.linspace(1,3,4))

print("\n===== Step 5: Linear algebra functions =====")
v = np.array([3,4])
print("norm(v):", np.linalg.norm(v))
print("inverse of a2:\n", linalg.inv(a2))
print("pseudo-inverse of a2:\n", linalg.pinv(a2))
U,S,Vh = linalg.svd(a2)
V = Vh.T
print("SVD - S:", S)

P,L,U = linalg.lu(a2)
print("LU decomposition:\nP:\n", P, "\nL:\n", L, "\nU:\n", U)

print("\n===== Step 6: Random indexing & logical operations =====")
a3 = np.array([0.1, 0.6, 0.3, 0.8])
print("a3 > 0.5:", a3 > 0.5)
print("indices where a3>0.5:", np.nonzero(a3>0.5)[0])
a3[a3<0.5] = 0
print("a3 with elements <0.5 zeroed out:", a3)

print("\n===== Step 7: Flatten & copy =====")
y = a.flatten()
print("Flattened a:\n", y)
y_copy = a.copy()
print("Copy of a:\n", y_copy)

print("\n===== Step 8: Concatenation =====")
c = np.array([[10,11,12]])
print("Concatenate rows:\n", np.vstack((a,c)))
print("Concatenate columns:\n", np.hstack((a.T,c.T)).T)


===== Step 1: Array properties =====
Array a:
 [[1 2 3]
 [4 5 6]]
ndims: 2
numel: 6
size: (2, 3)
size of 2nd dimension: 3

===== Step 2: Indexing & slicing =====
last element: 6
second row: [4 5 6]
first row to second row: [[1 2 3]
 [4 5 6]]
last 2 rows: [[1 2 3]
 [4 5 6]]
every other row: [[1 2 3]]
transpose: [[1 4]
 [2 5]
 [3 6]]

===== Step 3: Matrix operations =====
Matrix multiply a2 @ b:
 [[25 28]
 [57 64]]
Elementwise multiply a2 * b:
 [[ 7 16]
 [27 40]]
Elementwise divide a2 / b:
 [[0.14285714 0.25      ]
 [0.33333333 0.4       ]]
Elementwise power a2**3:
 [[ 1  8]
 [27 64]]
Conjugate transpose a2.conj().T:
 [[1 3]
 [2 4]]

===== Step 4: Special matrices =====
zeros 3x4:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones 3x4:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random 3x4:
 [[0.77395605 0.43887844 0.85859792 0.69736803]
 [0.09417735 0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802 0.92676499]]
l

In [ ]:
v = np.array([3,4])
print("norm:", np.linalg.norm(v))

a = np.array([[1,2],[3,4]])
print("inverse:", linalg.inv(a))
U,S,Vh = linalg.svd(a)
print("SVD S:", S)

norm: 5.0
inverse: [[-2.   1. ]
 [ 1.5 -0.5]]
SVD S: [5.4649857  0.36596619]
